### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by A1rPun** [mark-gerarts/automapper-plus-demo-app#1]
The post from [Elnur Abdurrakhimov](https://github.com/elnur) is not available anymore, I would like to read it but that is another problem ;).

> Note: you'll notice that this demo doesn't follow the Symfony standards by using a no-bundle approach. The architecture follows the core concepts explained in this post by Elnur Abdurrakhimov.

**Comment by mark-gerarts** [comment]
Thanks for reporting this! I'm gonna remove or rewrite the section, since Symfony 4 went this direction as well. The content is still available on the [internet archive](https://web.archive.org/web/20171029075211/http://elnur.pro/symfony-without-bundles) if you're interested.

**Comment by A1rPun** [comment]
By the power of webarchive! Thanks for the link. Consider this issue closed then, you can close it when the rewrite is done.
